image: quay.io/nasa_genelab/gl4u:gl4u_intro

tasks:
  - name: Start Jupyter Lab
    command: |
      source $HOME/miniconda3/etc/profile.d/conda.sh
      conda activate GL4U_Intro_JNs_2024
vscode:
  extensions:
    - mechatroner.rainbow-csv
    - ms-python.python
    - ms-toolsai.jupyter
    # - ms-toolsai.vscode-jupyter-powertoys
    - reditorsupport.r
    - esbenp.prettier-vscode 
    - mechatroner.rainbow-csv
