image: quay.io/nasa_genelab/gl4u:gl4u_intro_2024

tasks:
  - name: Setup Environment and Start Jupyter Lab
    init: echo "Initializing environment..."
    command: |
      # Set and export workDir
      export workDir="/workspace/GeneLab-Training/intro/SolarSystem"
      echo "export workDir=\"/workspace/GeneLab-Training/intro/SolarSystem\"" >> ~/.bashrc
      
      # Activate Conda environment
      source $HOME/miniconda3/etc/profile.d/conda.sh
      conda activate GL4U_Intro_JNs_2024
      
      # Set R variables (after Conda activation)
      echo "workDir <- Sys.getenv('workDir')" >> ~/.Rprofile
      
      echo "Environment setup complete. Starting Jupyter Lab..."
      
      # Start Jupyter Lab
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --LabServerApp.notebook_starts_kernel=False

ports:
  - port: 8888

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter