image: torresalexis/gl4u_rnaseq_2024:1.0.0

tasks:
  - init: |
      echo "Starting GL4U RNAseq Gitpod"
      source $HOME/miniconda3/etc/profile.d/conda.sh
    command: |
      conda activate gl4u_rnaseq_2024
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0'

ports:
  - port: 8888
