image: quay.io/nasa_genelab/gl4u:gl4u_intro_2024

tasks:
  - init: echo "Starting GL4U Intro 2024 Gitpod"
    command: |
      source $HOME/miniconda3/etc/profile.d/conda.sh
      conda activate GL4U_Intro_JNs_2024
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --LabServerApp.notebook_starts_kernel=False

ports:
  - port: 8888

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
