image: quay.io/nasa_genelab/gl4u:gl4u_rnaseq_2024

tasks:
  - init: |
      echo "Starting GL4U RNAseq Gitpod"
      source $HOME/miniconda3/etc/profile.d/conda.sh
    command: |
      conda activate gl4u_rnaseq_2024
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --LabServerApp.notebook_starts_kernel=False

ports:
  - port: 8888
