image: quay.io/nasa_genelab/gl4u:gl4u_intro_2024

tasks:
  - init: echo "Setting up environment"
    command: |
      # Unix variables
      export workDir="/workspace/GeneLab-Training/intro/SolarSystem"
      export my_var="Europa"
      export my_new_var="Europa is awesome."
      echo "export workDir=\"/workspace/GeneLab-Training/intro/SolarSystem\"" >> ~/.bashrc
      echo "export my_var=\"Europa\"" >> ~/.bashrc
      echo "export my_new_var=\"Europa is awesome.\"" >> ~/.bashrc
      
      # R variables
      echo "workDir <- Sys.getenv('workDir')" >> ~/.Rprofile
      echo "my_var <- Sys.getenv('my_var')" >> ~/.Rprofile
      echo "my_new_var <- Sys.getenv('my_new_var')" >> ~/.Rprofile
      echo "myDF <- read.table('/workspace/GeneLab-Training/intro/example.csv', sep = ',', row.names = 1, header = TRUE)" >> ~/.Rprofile
      
      # Source .bashrc to apply changes
      source ~/.bashrc
      
      # Activate Conda environment and start Jupyter Lab
      source $HOME/miniconda3/etc/profile.d/conda.sh
      conda activate GL4U_Intro_JNs_2024
      jupyter lab --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0' --LabServerApp.notebook_starts_kernel=False


ports:
  - port: 8888

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true